# This is an example configuration file for a web scraping project.
# It contains the required settings, such as database connection details and logging configuration.

# -- Database Configuration --
# For MySQL
# DATABASE:
#   DBTYPE: MySQL                   # The type of database (mysql or sqlite)
#   HOST: <host>                 # The host where the database is located
#   USER: <user>                      # The username to connect to the database
#   PASSWORD: <password>            # The password for the database user
#   DBNAME: <db-name>               # The name of the database to connect to
#   DBPATH: <path/to/database.sql>  # The path to the SQLite database file

# For SQLite
DATABASE:
  DBTYPE: SQLite                    # The type of database (mysql or sqlite)
  DBPATH: data/database.db          # The path to the SQLite database file
# Note: The host, user, and password fields are not needed for SQLite

# -- Scraping Configuration --
# TODO: Add scraping configuration settings, such as timeouts, user agents, etc.

# -- Logging Configuration --
LOGGING:
  LEVEL: DEBUG                      # The logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  FILENAME: logs/app.log            # The file where logs will be saved
  HANDLERS: [file, console]         # The handlers to use for logging (console, file, or both)