[project]
name = "web-scraping-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "lxml>=5.3.2",
    "streamlit>=1.44.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
